<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}" @class(['dark'=> ($appearance ?? 'system') == 'dark'])>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Student Transaction Ledger</title>
    <link rel="preconnect" href="https://fonts.bunny.net">
    <link href="https://fonts.bunny.net/css?family=inter:400,500,600,700" rel="stylesheet" />
    <style>
        * {
            font-family: 'Inter', 'DejaVu Sans', sans-serif;
        }

        body {
            font-size: 12px;
            color: #111827;
            margin: 12px;
        }

        /* ===== HEADER ===== */
        .report-header {
            border-bottom: 2px solid #111827;
            margin-bottom: 16px;
            padding-bottom: 10px;
        }

        .header-row {
            display: flex;
            align-items: center;
            justify-content: space-between;
        }

        .company-logo img {
            max-width: 100px;
        }

        .report-title h1 {
            margin: 0;
            font-size: 18px;
            font-weight: 700;
            letter-spacing: 1px;
            text-align: center;
        }

        .report-meta {
            font-size: 11px;
            text-align: right;
            color: #374151;
        }

        /* ===== STUDENT INFO ===== */
        .info-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 14px;
            background: #f9fafb;
        }

        .info-table th {
            text-align: left;
            width: 180px;
            padding: 6px 8px;
            background: #f3f4f6;
            font-weight: 600;
        }

        .info-table td {
            padding: 6px 8px;
        }

        /* ===== LEDGER TABLE ===== */
        .trial-table {
            width: 100%;
            border-collapse: collapse;
            font-size: 11.5px;
        }

        .trial-table th {
            padding: 8px;
            text-align: right;
            border-bottom: 2px solid #111827;
            font-weight: 600;
            background: #fafafa;
        }

        .trial-table th:nth-child(1),
        .trial-table th:nth-child(2),
        .trial-table th:nth-child(3),
        .trial-table td:nth-child(1),
        
        .trial-table td:nth-child(2),
        .trial-table td:nth-child(3) {
            text-align: left;
        }
        .trial-table td {
            padding: 7px 8px;
            border-bottom: 1px solid #e5e7eb;
            text-align: right;
        }

        .account-name {
            padding-left: 4px;
        }

        /* ===== TOTAL ROW ===== */
        .total-row td {
            font-weight: 700;
            border-top: 2px solid #111827;
            background: #f3f4f6;
            text-align: right;
        }

        /* ===== FOOTER ===== */
        .footer {
            width: 100%;
            margin-top: 40px;
            font-size: 10px;
        }

        .sign {
            width: 33%;
            text-align: center;
            padding-top: 35px;
        }

        .sign span {
            display: block;
            border-top: 1px solid #000;
            margin-top: 5px;
        }
    </style>
</head>

<body>
    <!-- Header -->
    <div class="report-header">
        <div class="header-row">
            <!-- LEFT: Logo & Company -->
            <div class="header-col company-logo">
                <img src="{{ public_path('storage/company/' . $company->companylogo) }}" alt="Company Logo">
            </div>

            <!-- CENTER: Report Title -->
            <div class="header-col report-title">
                <h1>Student Ledger</h1>
            </div>

            <!-- RIGHT: Meta Info -->
            <div class="header-col report-meta">
                <p><strong>Date:</strong> {{ now()->format('d M Y') }}</p>
                <p><strong>Generated By:</strong> {{ auth()->user()->name ?? 'System' }}</p>
            </div>
        </div>
    </div>

    <!-- Student Info -->
    <table class="info-table">
        <tr>
            <th>Student ID</th>
            <td>{{ $student->student_id }}</td>
        </tr>
        <tr>
            <th>Student Name</th>
            <td>{{ $student->fname }} {{ $student->lname }}</td>
        </tr>
        <tr>
            <th>Student Email</th>
            <td>{{ $student->email ?? '-' }}</td>
        </tr>
        <tr>
            <th>Student Phone</th>
            <td>{{ $student->phone ?? '-' }}</td>
        </tr>
        <tr>
            <th>Destination Country</th>
            <td>{{ $student->country->name ?? '-' }}</td>
        </tr>
    </table>
    <!-- TRIAL BALANCE TABLE -->
    <table class="trial-table">
        <thead>
            <tr>
                <th width="10%">Sl</th>
                <th width="15%">Date</th>
                <th width="45%">Particulars</th>
                <th width="15%">Debit (BDT)</th>
                <th width="15%">Credit (BDT)</th>
            </tr>
        </thead>

        <tbody>
            @php
            $sl = 1;
            $totalDebit = 0;
            $totalCredit = 0;
            @endphp
            @foreach ($data as $student)

            <tr>
                <td>{{ $sl++ }}</td>
                <td>{{ $student['mrdate']}}</td>
                <td class="account-name">{{ $student['feesname'] }}
                    <small style="color:#6b7280;">({{ $student['mrno'] }})</small>
                </td>
                <td>
                    @if ($student['primeamt'] > 0)
                    @php $totalDebit += abs($student['primeamt']); @endphp
                    {{ $student['primeamt'] }}
                    @endif
                </td>
                <td>
                    @if ($student['primeamt'] < 0)
                        @php $totalCredit +=abs($student['primeamt']); @endphp
                        {{ abs($student['primeamt']) }}
                        @endif
                        </td>
            </tr>
            @endforeach


            <!-- TOTAL -->
            <tr class="total-row">
                <td colspan="3">TOTAL</td>
                <td><strong>{{ number_format($totalDebit, 2) }}</strong></td>
                <td><strong>{{ number_format($totalCredit, 2) }}</strong></td>
            </tr>
        </tbody>
    </table>

    <!-- FOOTER -->
    <table class="footer">
        <tr>
            <td class="sign"><span>Prepared By</span></td>
            <td class="sign"><span>Checked By</span></td>
            <td class="sign"><span>Approved By</span></td>
        </tr>
    </table>




</body>

</html>